server:
  port: 8080
  servlet:
    context-path: /user-service

spring:
  # Postgresql Config
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      show_sql: true
      format_sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 25MB

file:
  upload-dir: /Users/images/

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

modules:
  endpoints:
    user-service:
    recommend-service:
    relation-service:
    chat-service:

