apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-service-pv
  namespace: backend
spec:
  capacity:
    storage: 20Gi  # Longhorn 볼륨의 크기를 정의합니다.
  volumeMode: Filesystem  # 블록 장치 또는 파일 시스템을 정의합니다. 일반적으로 파일 시스템을 사용합니다.
  accessModes:
    - ReadWriteMany  # RWO 모드는 단일 노드에서 읽기/쓰기가 가능합니다. Longhorn에서는 주로 이 모드를 사용합니다.
  persistentVolumeReclaimPolicy: Retain  # PV가 사용 후에 어떻게 처리될지를 정의합니다. Retain은 삭제 후에도 데이터를 유지합니다.
  storageClassName: longhorn  # Longhorn 스토리지 클래스와 연결합니다.
  csi:
    driver: driver.longhorn.io  # Longhorn CSI 드라이버를 사용합니다.
    fsType: ext4  # 파일 시스템 유형을 지정합니다. ext4가 일반적으로 사용됩니다.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-service-pvc
  namespace: backend
spec:
  accessModes:
    - ReadWriteMany  # RWO 모드는 단일 노드에서 읽기/쓰기가 가능하게 합니다.
  resources:
    requests:
      storage: 20Gi  # 요청하는 스토리지의 크기입니다. PV와 일치해야 합니다.(PV:PVC=1:1)
  storageClassName: longhorn  # Longhorn 스토리지 클래스를 지정하여 Longhorn 볼륨을 사용하도록 합니다.