name: ArgoCD Update Manifest

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy-to-k8s:
    name: Push Manifest
    runs-on: ubuntu-latest
    steps:

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # pulls all history and tags for Lerna to detect which packages changed
          token: ${{ steps.app-token.outputs.token }}

      - name: Get the latest commit hash
        run: |
          SHORT_HASH=$(echo "${{ github.event.workflow_run.head_commit.id }}" | cut -c1-7)
          echo "HASH=$SHORT_HASH" >> $GITHUB_ENV

      - name: Change manifest
        run: sed -i "s|${{ secrets.DOCKER_USERNAME }}/watermelon-user-service:\s*[^ ]*|${{ secrets.DOCKER_USERNAME }}/watermelon-user-service:${{ env.HASH }}|g" k8s/deploy.yaml

      - name: git push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config credential.helper store
          git add k8s/deploy.yaml
          git commit -m ":tada: Update: Image [${{ env.HASH }}]"
          git push
